language: ruby
cache: bundler

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

matrix:
  fast_finish: true

before_install:
  - cp gemrc ~/.gemrc

script: "bundle exec rspec"
